[package]
name = "ggl"
version = "0.1.0"
edition = "2021"


[dependencies]
nalgebra-glm = "^0.17.0"
image = "^0.24.2"
bytemuck = "1.7"
memoffset = "0.6"
tracing = "0.1"
glutin = "0.28.0"
glow = "0.10.0"